version: "2"
services:
  web:
    container_name: product_service
    build: 
      context: .
      args:
        - NODE_ENV="DEV"
        - MONGO_DEV_URL=mongodb://mongo/testproject1
    ports:
      - "4001:4001"

      
    # links:
    #   - mongo
  # mongo:
  #   container_name: product_mongo
  #   image: mongo
  #   ports:
  #     - "27017:27017"